
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

// This is class that describes you smart contract.
contract map_opt {
    // Contract can have an instance variables.
    // In this example instance variable `timestamp` is used to store the time of `constructor` or `touch`
    // function call
    mapping (uint => uint) myMap;

    // Contract can have a `constructor` – function that will be called when contract will be deployed to the blockchain.
    // In this example constructor adds current time to the instance variable.
    // All contracts need call tvm.accept(); for succeeded deploy
    constructor() public {
        // Check that contract's public key is set
        require(tvm.pubkey() != 0, 101);
        // Check that message has signature (msg.pubkey() is not zero) and
        // message is signed with the owner's private key
        require(msg.pubkey() == tvm.pubkey(), 102);
        // The current smart contract agrees to buy some gas to finish the
        // current transaction. This actions required to process external
        // messages, which bring no value (henceno gas) with themselves.
        tvm.accept();

        myMap[4] = 6;
        myMap[19] = 3;
        myMap[1] = 17;
        myMap[5] = 9;
        myMap[33] = 2;
    }

    function renderHelloWorld () public pure returns (string) {
        return 'helloWorld';
    }

    function getList() public returns (uint[]) {
        tvm.accept();
        optional(uint, uint) currentOpt = myMap.min();
        uint[] resArr;

        while (currentOpt.hasValue()) {
            (uint key, uint val) = currentOpt.get();
            resArr.push(val);
            currentOpt = myMap.next(key);
        }

        return resArr;
    }

}
